// This file was auto-generated by Quasalang

import enUS from './en-US'
import fr from './fr'
import hi_IN from './hi_IN'
import ro_RO from './ro_RO'
import ja from './ja'
import ko from './ko'
import ru_RU from './ru_RU'
import es from './es'
import zh from './zh'
import ar from './ar'
import pt from './pt'
import it_IT from './it_IT'

export default { 
	'en-US': enUS, // English
	'fr': fr, // French
	'hi_IN': hi_IN, // Hindi (India)
	'ro_RO': ro_RO, // Romanian (Romania)
	'ja': ja, // Japanese
	'ko': ko, // Korean
	'ru_RU': ru_RU, // Russian (Russia)
	'es': es, // Spanish
	'zh': zh, // Chinese
	'ar': ar, // Arabic
	'pt': pt, // Portuguese
	'it_IT': it_IT, // Italian (Italy)
}