export const get = ({ filter }) => {
  return new Promise((resolve, reject) => {
    try {
      const needle = filter.toLowerCase();
      const data = countries.filter(
        ({ name }) => name.toLowerCase().indexOf(needle) > -1
      );
      resolve({ data, meta: { current_page: 1, last_page: 1 } });
    } catch (error) {
      reject(error);
    }
  });
};

export const getCurrencySymbol = (val) => {
  return new Promise((resolve, reject) => {
    try {
      const needle = val.toLowerCase();
      const data = countries.find((item) => item.currency === needle);
      resolve(data);
    } catch (error) {
      reject(error);
    }
  });
};

export const countries = [
  {
    name: "Afghanistan",
    iso2: "AF",
    currency: "afn",
    currency_symbol: "؋",
    phone_code: "+93",
    emoji: "🇦🇫",
  },
  {
    name: "Aland Islands",
    iso2: "AX",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+358-18",
    emoji: "🇦🇽",
  },
  {
    name: "Albania",
    iso2: "AL",
    currency: "all",
    currency_symbol: "Lek",
    phone_code: "+355",
    emoji: "🇦🇱",
  },
  {
    name: "Algeria",
    iso2: "DZ",
    currency: "dzd",
    currency_symbol: "دج",
    phone_code: "+213",
    emoji: "🇩🇿",
  },
  {
    name: "American Samoa",
    iso2: "AS",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+1-684",
    emoji: "🇦🇸",
  },
  {
    name: "Andorra",
    iso2: "AD",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+376",
    emoji: "🇦🇩",
  },
  {
    name: "Angola",
    iso2: "AO",
    currency: "aoa",
    currency_symbol: "Kz",
    phone_code: "+244",
    emoji: "🇦🇴",
  },
  {
    name: "Anguilla",
    iso2: "AI",
    currency: "xcd",
    currency_symbol: "$",
    phone_code: "+1-264",
    emoji: "🇦🇮",
  },
  {
    name: "Antarctica",
    iso2: "AQ",
    currency: "aad",
    currency_symbol: "$",
    phone_code: "+672",
    emoji: "🇦🇶",
  },
  {
    name: "Antigua And Barbuda",
    iso2: "AG",
    currency: "xcd",
    currency_symbol: "$",
    phone_code: "+1-268",
    emoji: "🇦🇬",
  },
  {
    name: "Argentina",
    iso2: "AR",
    currency: "ars",
    currency_symbol: "$",
    phone_code: "+54",
    emoji: "🇦🇷",
  },
  {
    name: "Armenia",
    iso2: "AM",
    currency: "amd",
    currency_symbol: "֏",
    phone_code: "+374",
    emoji: "🇦🇲",
  },
  {
    name: "Aruba",
    iso2: "AW",
    currency: "awg",
    currency_symbol: "ƒ",
    phone_code: "+297",
    emoji: "🇦🇼",
  },
  {
    name: "Australia",
    iso2: "AU",
    currency: "aud",
    currency_symbol: "$",
    phone_code: "+61",
    emoji: "🇦🇺",
  },
  {
    name: "Austria",
    iso2: "AT",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+43",
    emoji: "🇦🇹",
  },
  {
    name: "Azerbaijan",
    iso2: "AZ",
    currency: "azn",
    currency_symbol: "m",
    phone_code: "+994",
    emoji: "🇦🇿",
  },
  {
    name: "Bahamas The",
    iso2: "BS",
    currency: "bsd",
    currency_symbol: "B$",
    phone_code: "+1-242",
    emoji: "🇧🇸",
  },
  {
    name: "Bahrain",
    iso2: "BH",
    currency: "bhd",
    currency_symbol: ".د.ب",
    phone_code: "+973",
    emoji: "🇧🇭",
  },
  {
    name: "Bangladesh",
    iso2: "BD",
    currency: "bdt",
    currency_symbol: "৳",
    phone_code: "+880",
    emoji: "🇧🇩",
  },
  {
    name: "Barbados",
    iso2: "BB",
    currency: "bbd",
    currency_symbol: "Bds$",
    phone_code: "+1-246",
    emoji: "🇧🇧",
  },
  {
    name: "Belarus",
    iso2: "BY",
    currency: "byn",
    currency_symbol: "Br",
    phone_code: "+375",
    emoji: "🇧🇾",
  },
  {
    name: "Belgium",
    iso2: "BE",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+32",
    emoji: "🇧🇪",
  },
  {
    name: "Belize",
    iso2: "BZ",
    currency: "bzd",
    currency_symbol: "$",
    phone_code: "+501",
    emoji: "🇧🇿",
  },
  {
    name: "Benin",
    iso2: "BJ",
    currency: "xof",
    currency_symbol: "CFA",
    phone_code: "+229",
    emoji: "🇧🇯",
  },
  {
    name: "Bermuda",
    iso2: "BM",
    currency: "bmd",
    currency_symbol: "$",
    phone_code: "+1-441",
    emoji: "🇧🇲",
  },
  {
    name: "Bhutan",
    iso2: "BT",
    currency: "btn",
    currency_symbol: "Nu.",
    phone_code: "+975",
    emoji: "🇧🇹",
  },
  {
    name: "Bolivia",
    iso2: "BO",
    currency: "bob",
    currency_symbol: "Bs.",
    phone_code: "+591",
    emoji: "🇧🇴",
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    iso2: "BQ",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+599",
    emoji: "🇧🇶",
  },
  {
    name: "Bosnia and Herzegovina",
    iso2: "BA",
    currency: "bam",
    currency_symbol: "KM",
    phone_code: "+387",
    emoji: "🇧🇦",
  },
  {
    name: "Botswana",
    iso2: "BW",
    currency: "bwp",
    currency_symbol: "P",
    phone_code: "+267",
    emoji: "🇧🇼",
  },
  {
    name: "Bouvet Island",
    iso2: "BV",
    currency: "nok",
    currency_symbol: "kr",
    phone_code: "+0055",
    emoji: "🇧🇻",
  },
  {
    name: "Brazil",
    iso2: "BR",
    currency: "brl",
    currency_symbol: "R$",
    phone_code: "+55",
    emoji: "🇧🇷",
  },
  {
    name: "British Indian Ocean Territory",
    iso2: "IO",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+246",
    emoji: "🇮🇴",
  },
  {
    name: "Brunei",
    iso2: "BN",
    currency: "bnd",
    currency_symbol: "B$",
    phone_code: "+673",
    emoji: "🇧🇳",
  },
  {
    name: "Bulgaria",
    iso2: "BG",
    currency: "bgn",
    currency_symbol: "Лв.",
    phone_code: "+359",
    emoji: "🇧🇬",
  },
  {
    name: "Burkina Faso",
    iso2: "BF",
    currency: "xof",
    currency_symbol: "CFA",
    phone_code: "+226",
    emoji: "🇧🇫",
  },
  {
    name: "Burundi",
    iso2: "BI",
    currency: "bif",
    currency_symbol: "FBu",
    phone_code: "+257",
    emoji: "🇧🇮",
  },
  {
    name: "Cambodia",
    iso2: "KH",
    currency: "khr",
    currency_symbol: "KHR",
    phone_code: "+855",
    emoji: "🇰🇭",
  },
  {
    name: "Cameroon",
    iso2: "CM",
    currency: "xaf",
    currency_symbol: "FCFA",
    phone_code: "+237",
    emoji: "🇨🇲",
  },
  {
    name: "Canada",
    iso2: "CA",
    currency: "cad",
    currency_symbol: "$",
    phone_code: "+1",
    emoji: "🇨🇦",
  },
  {
    name: "Cape Verde",
    iso2: "CV",
    currency: "cve",
    currency_symbol: "$",
    phone_code: "+238",
    emoji: "🇨🇻",
  },
  {
    name: "Cayman Islands",
    iso2: "KY",
    currency: "kyd",
    currency_symbol: "$",
    phone_code: "+1-345",
    emoji: "🇰🇾",
  },
  {
    name: "Central African Republic",
    iso2: "CF",
    currency: "xaf",
    currency_symbol: "FCFA",
    phone_code: "+236",
    emoji: "🇨🇫",
  },
  {
    name: "Chad",
    iso2: "TD",
    currency: "xaf",
    currency_symbol: "FCFA",
    phone_code: "+235",
    emoji: "🇹🇩",
  },
  {
    name: "Chile",
    iso2: "CL",
    currency: "clp",
    currency_symbol: "$",
    phone_code: "+56",
    emoji: "🇨🇱",
  },
  {
    name: "China",
    iso2: "CN",
    currency: "cny",
    currency_symbol: "¥",
    phone_code: "+86",
    emoji: "🇨🇳",
  },
  {
    name: "Christmas Island",
    iso2: "CX",
    currency: "aud",
    currency_symbol: "$",
    phone_code: "+61",
    emoji: "🇨🇽",
  },
  {
    name: "Cocos (Keeling) Islands",
    iso2: "CC",
    currency: "aud",
    currency_symbol: "$",
    phone_code: "+61",
    emoji: "🇨🇨",
  },
  {
    name: "Colombia",
    iso2: "CO",
    currency: "cop",
    currency_symbol: "$",
    phone_code: "+57",
    emoji: "🇨🇴",
  },
  {
    name: "Comoros",
    iso2: "KM",
    currency: "kmf",
    currency_symbol: "CF",
    phone_code: "+269",
    emoji: "🇰🇲",
  },
  {
    name: "Congo",
    iso2: "CG",
    currency: "xaf",
    currency_symbol: "FC",
    phone_code: "+242",
    emoji: "🇨🇬",
  },
  {
    name: "Cook Islands",
    iso2: "CK",
    currency: "nzd",
    currency_symbol: "$",
    phone_code: "+682",
    emoji: "🇨🇰",
  },
  {
    name: "Costa Rica",
    iso2: "CR",
    currency: "crc",
    currency_symbol: "₡",
    phone_code: "+506",
    emoji: "🇨🇷",
  },
  {
    name: "Cote D'Ivoire (Ivory Coast)",
    iso2: "CI",
    currency: "xof",
    currency_symbol: "CFA",
    phone_code: "+225",
    emoji: "🇨🇮",
  },
  {
    name: "Croatia",
    iso2: "HR",
    currency: "hrk",
    currency_symbol: "kn",
    phone_code: "+385",
    emoji: "🇭🇷",
  },
  {
    name: "Cuba",
    iso2: "CU",
    currency: "cup",
    currency_symbol: "$",
    phone_code: "+53",
    emoji: "🇨🇺",
  },
  {
    name: "Curaçao",
    iso2: "CW",
    currency: "ang",
    currency_symbol: "ƒ",
    phone_code: "+599",
    emoji: "🇨🇼",
  },
  {
    name: "Cyprus",
    iso2: "CY",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+357",
    emoji: "🇨🇾",
  },
  {
    name: "Czech Republic",
    iso2: "CZ",
    currency: "czk",
    currency_symbol: "Kč",
    phone_code: "+420",
    emoji: "🇨🇿",
  },
  {
    name: "Democratic Republic of the Congo",
    iso2: "CD",
    currency: "cdf",
    currency_symbol: "FC",
    phone_code: "+243",
    emoji: "🇨🇩",
  },
  {
    name: "Denmark",
    iso2: "DK",
    currency: "dkk",
    currency_symbol: "Kr.",
    phone_code: "+45",
    emoji: "🇩🇰",
  },
  {
    name: "Djibouti",
    iso2: "DJ",
    currency: "djf",
    currency_symbol: "Fdj",
    phone_code: "+253",
    emoji: "🇩🇯",
  },
  {
    name: "Dominica",
    iso2: "DM",
    currency: "xcd",
    currency_symbol: "$",
    phone_code: "+1-767",
    emoji: "🇩🇲",
  },
  {
    name: "Dominican Republic",
    iso2: "DO",
    currency: "dop",
    currency_symbol: "$",
    phone_code: "+1-809 and 1-829",
    emoji: "🇩🇴",
  },
  {
    name: "East Timor",
    iso2: "TL",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+670",
    emoji: "🇹🇱",
  },
  {
    name: "Ecuador",
    iso2: "EC",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+593",
    emoji: "🇪🇨",
  },
  {
    name: "Egypt",
    iso2: "EG",
    currency: "egp",
    currency_symbol: "ج.م",
    phone_code: "+20",
    emoji: "🇪🇬",
  },
  {
    name: "El Salvador",
    iso2: "SV",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+503",
    emoji: "🇸🇻",
  },
  {
    name: "Equatorial Guinea",
    iso2: "GQ",
    currency: "xaf",
    currency_symbol: "FCFA",
    phone_code: "+240",
    emoji: "🇬🇶",
  },
  {
    name: "Eritrea",
    iso2: "ER",
    currency: "ern",
    currency_symbol: "Nfk",
    phone_code: "+291",
    emoji: "🇪🇷",
  },
  {
    name: "Estonia",
    iso2: "EE",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+372",
    emoji: "🇪🇪",
  },
  {
    name: "Ethiopia",
    iso2: "ET",
    currency: "etb",
    currency_symbol: "Nkf",
    phone_code: "+251",
    emoji: "🇪🇹",
  },
  {
    name: "Falkland Islands",
    iso2: "FK",
    currency: "fkp",
    currency_symbol: "£",
    phone_code: "+500",
    emoji: "🇫🇰",
  },
  {
    name: "Faroe Islands",
    iso2: "FO",
    currency: "dkk",
    currency_symbol: "Kr.",
    phone_code: "+298",
    emoji: "🇫🇴",
  },
  {
    name: "Fiji Islands",
    iso2: "FJ",
    currency: "fjd",
    currency_symbol: "FJ$",
    phone_code: "+679",
    emoji: "🇫🇯",
  },
  {
    name: "Finland",
    iso2: "FI",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+358",
    emoji: "🇫🇮",
  },
  {
    name: "France",
    iso2: "FR",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+33",
    emoji: "🇫🇷",
  },
  {
    name: "French Guiana",
    iso2: "GF",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+594",
    emoji: "🇬🇫",
  },
  {
    name: "French Polynesia",
    iso2: "PF",
    currency: "xpf",
    currency_symbol: "₣",
    phone_code: "+689",
    emoji: "🇵🇫",
  },
  {
    name: "French Southern Territories",
    iso2: "TF",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+262",
    emoji: "🇹🇫",
  },
  {
    name: "Gabon",
    iso2: "GA",
    currency: "xaf",
    currency_symbol: "FCFA",
    phone_code: "+241",
    emoji: "🇬🇦",
  },
  {
    name: "Gambia The",
    iso2: "GM",
    currency: "gmd",
    currency_symbol: "D",
    phone_code: "+220",
    emoji: "🇬🇲",
  },
  {
    name: "Georgia",
    iso2: "GE",
    currency: "gel",
    currency_symbol: "ლ",
    phone_code: "+995",
    emoji: "🇬🇪",
  },
  {
    name: "Germany",
    iso2: "DE",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+49",
    emoji: "🇩🇪",
  },
  {
    name: "Ghana",
    iso2: "GH",
    currency: "ghs",
    currency_symbol: "GH₵",
    phone_code: "+233",
    emoji: "🇬🇭",
  },
  {
    name: "Gibraltar",
    iso2: "GI",
    currency: "gip",
    currency_symbol: "£",
    phone_code: "+350",
    emoji: "🇬🇮",
  },
  {
    name: "Greece",
    iso2: "GR",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+30",
    emoji: "🇬🇷",
  },
  {
    name: "Greenland",
    iso2: "GL",
    currency: "dkk",
    currency_symbol: "Kr.",
    phone_code: "+299",
    emoji: "🇬🇱",
  },
  {
    name: "Grenada",
    iso2: "GD",
    currency: "xcd",
    currency_symbol: "$",
    phone_code: "+1-473",
    emoji: "🇬🇩",
  },
  {
    name: "Guadeloupe",
    iso2: "GP",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+590",
    emoji: "🇬🇵",
  },
  {
    name: "Guam",
    iso2: "GU",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+1-671",
    emoji: "🇬🇺",
  },
  {
    name: "Guatemala",
    iso2: "GT",
    currency: "gtq",
    currency_symbol: "Q",
    phone_code: "+502",
    emoji: "🇬🇹",
  },
  {
    name: "Guernsey and Alderney",
    iso2: "GG",
    currency: "gbp",
    currency_symbol: "£",
    phone_code: "+44-1481",
    emoji: "🇬🇬",
  },
  {
    name: "Guinea",
    iso2: "GN",
    currency: "gnf",
    currency_symbol: "FG",
    phone_code: "+224",
    emoji: "🇬🇳",
  },
  {
    name: "Guinea-Bissau",
    iso2: "GW",
    currency: "xof",
    currency_symbol: "CFA",
    phone_code: "+245",
    emoji: "🇬🇼",
  },
  {
    name: "Guyana",
    iso2: "GY",
    currency: "gyd",
    currency_symbol: "$",
    phone_code: "+592",
    emoji: "🇬🇾",
  },
  {
    name: "Haiti",
    iso2: "HT",
    currency: "htg",
    currency_symbol: "G",
    phone_code: "+509",
    emoji: "🇭🇹",
  },
  {
    name: "Heard Island and McDonald Islands",
    iso2: "HM",
    currency: "aud",
    currency_symbol: "$",
    phone_code: "+672",
    emoji: "🇭🇲",
  },
  {
    name: "Honduras",
    iso2: "HN",
    currency: "hnl",
    currency_symbol: "L",
    phone_code: "+504",
    emoji: "🇭🇳",
  },
  {
    name: "Hong Kong S.A.R.",
    iso2: "HK",
    currency: "hkd",
    currency_symbol: "$",
    phone_code: "+852",
    emoji: "🇭🇰",
  },
  {
    name: "Hungary",
    iso2: "HU",
    currency: "huf",
    currency_symbol: "Ft",
    phone_code: "+36",
    emoji: "🇭🇺",
  },
  {
    name: "Iceland",
    iso2: "IS",
    currency: "isk",
    currency_symbol: "kr",
    phone_code: "+354",
    emoji: "🇮🇸",
  },
  {
    name: "India",
    iso2: "IN",
    currency: "inr",
    currency_symbol: "₹",
    phone_code: "+91",
    emoji: "🇮🇳",
  },
  {
    name: "Indonesia",
    iso2: "ID",
    currency: "idr",
    currency_symbol: "Rp",
    phone_code: "+62",
    emoji: "🇮🇩",
  },
  {
    name: "Iran",
    iso2: "IR",
    currency: "irr",
    currency_symbol: "﷼",
    phone_code: "+98",
    emoji: "🇮🇷",
  },
  {
    name: "Iraq",
    iso2: "IQ",
    currency: "iqd",
    currency_symbol: "د.ع",
    phone_code: "+964",
    emoji: "🇮🇶",
  },
  {
    name: "Ireland",
    iso2: "IE",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+353",
    emoji: "🇮🇪",
  },
  {
    name: "Israel",
    iso2: "IL",
    currency: "ils",
    currency_symbol: "₪",
    phone_code: "+972",
    emoji: "🇮🇱",
  },
  {
    name: "Italy",
    iso2: "IT",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+39",
    emoji: "🇮🇹",
  },
  {
    name: "Jamaica",
    iso2: "JM",
    currency: "jmd",
    currency_symbol: "J$",
    phone_code: "+1-876",
    emoji: "🇯🇲",
  },
  {
    name: "Japan",
    iso2: "JP",
    currency: "jpy",
    currency_symbol: "¥",
    phone_code: "+81",
    emoji: "🇯🇵",
  },
  {
    name: "Jersey",
    iso2: "JE",
    currency: "gbp",
    currency_symbol: "£",
    phone_code: "+44-1534",
    emoji: "🇯🇪",
  },
  {
    name: "Jordan",
    iso2: "JO",
    currency: "jod",
    currency_symbol: "ا.د",
    phone_code: "+962",
    emoji: "🇯🇴",
  },
  {
    name: "Kazakhstan",
    iso2: "KZ",
    currency: "kzt",
    currency_symbol: "лв",
    phone_code: "+7",
    emoji: "🇰🇿",
  },
  {
    name: "Kenya",
    iso2: "KE",
    currency: "kes",
    currency_symbol: "KSh",
    phone_code: "+254",
    emoji: "🇰🇪",
  },
  {
    name: "Kiribati",
    iso2: "KI",
    currency: "aud",
    currency_symbol: "$",
    phone_code: "+686",
    emoji: "🇰🇮",
  },
  {
    name: "Kosovo",
    iso2: "XK",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+383",
    emoji: "🇽🇰",
  },
  {
    name: "Kuwait",
    iso2: "KW",
    currency: "kwd",
    currency_symbol: "ك.د",
    phone_code: "+965",
    emoji: "🇰🇼",
  },
  {
    name: "Kyrgyzstan",
    iso2: "KG",
    currency: "kgs",
    currency_symbol: "лв",
    phone_code: "+996",
    emoji: "🇰🇬",
  },
  {
    name: "Laos",
    iso2: "LA",
    currency: "lak",
    currency_symbol: "₭",
    phone_code: "+856",
    emoji: "🇱🇦",
  },
  {
    name: "Latvia",
    iso2: "LV",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+371",
    emoji: "🇱🇻",
  },
  {
    name: "Lebanon",
    iso2: "LB",
    currency: "lbp",
    currency_symbol: "£",
    phone_code: "+961",
    emoji: "🇱🇧",
  },
  {
    name: "Lesotho",
    iso2: "LS",
    currency: "lsl",
    currency_symbol: "L",
    phone_code: "+266",
    emoji: "🇱🇸",
  },
  {
    name: "Liberia",
    iso2: "LR",
    currency: "lrd",
    currency_symbol: "$",
    phone_code: "+231",
    emoji: "🇱🇷",
  },
  {
    name: "Libya",
    iso2: "LY",
    currency: "lyd",
    currency_symbol: "د.ل",
    phone_code: "+218",
    emoji: "🇱🇾",
  },
  {
    name: "Liechtenstein",
    iso2: "LI",
    currency: "chf",
    currency_symbol: "CHf",
    phone_code: "+423",
    emoji: "🇱🇮",
  },
  {
    name: "Lithuania",
    iso2: "LT",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+370",
    emoji: "🇱🇹",
  },
  {
    name: "Luxembourg",
    iso2: "LU",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+352",
    emoji: "🇱🇺",
  },
  {
    name: "Macau S.A.R.",
    iso2: "MO",
    currency: "mop",
    currency_symbol: "$",
    phone_code: "+853",
    emoji: "🇲🇴",
  },
  {
    name: "Macedonia",
    iso2: "MK",
    currency: "mkd",
    currency_symbol: "ден",
    phone_code: "+389",
    emoji: "🇲🇰",
  },
  {
    name: "Madagascar",
    iso2: "MG",
    currency: "mga",
    currency_symbol: "Ar",
    phone_code: "+261",
    emoji: "🇲🇬",
  },
  {
    name: "Malawi",
    iso2: "MW",
    currency: "mwk",
    currency_symbol: "MK",
    phone_code: "+265",
    emoji: "🇲🇼",
  },
  {
    name: "Malaysia",
    iso2: "MY",
    currency: "myr",
    currency_symbol: "RM",
    phone_code: "+60",
    emoji: "🇲🇾",
  },
  {
    name: "Maldives",
    iso2: "MV",
    currency: "mvr",
    currency_symbol: "Rf",
    phone_code: "+960",
    emoji: "🇲🇻",
  },
  {
    name: "Mali",
    iso2: "ML",
    currency: "xof",
    currency_symbol: "CFA",
    phone_code: "+223",
    emoji: "🇲🇱",
  },
  {
    name: "Malta",
    iso2: "MT",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+356",
    emoji: "🇲🇹",
  },
  {
    name: "Man (Isle of)",
    iso2: "IM",
    currency: "gbp",
    currency_symbol: "£",
    phone_code: "+44-1624",
    emoji: "🇮🇲",
  },
  {
    name: "Marshall Islands",
    iso2: "MH",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+692",
    emoji: "🇲🇭",
  },
  {
    name: "Martinique",
    iso2: "MQ",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+596",
    emoji: "🇲🇶",
  },
  {
    name: "Mauritania",
    iso2: "MR",
    currency: "mro",
    currency_symbol: "MRU",
    phone_code: "+222",
    emoji: "🇲🇷",
  },
  {
    name: "Mauritius",
    iso2: "MU",
    currency: "mur",
    currency_symbol: "₨",
    phone_code: "+230",
    emoji: "🇲🇺",
  },
  {
    name: "Mayotte",
    iso2: "YT",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+262",
    emoji: "🇾🇹",
  },
  {
    name: "Mexico",
    iso2: "MX",
    currency: "mxn",
    currency_symbol: "$",
    phone_code: "+52",
    emoji: "🇲🇽",
  },
  {
    name: "Micronesia",
    iso2: "FM",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+691",
    emoji: "🇫🇲",
  },
  {
    name: "Moldova",
    iso2: "MD",
    currency: "mdl",
    currency_symbol: "L",
    phone_code: "+373",
    emoji: "🇲🇩",
  },
  {
    name: "Monaco",
    iso2: "MC",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+377",
    emoji: "🇲🇨",
  },
  {
    name: "Mongolia",
    iso2: "MN",
    currency: "mnt",
    currency_symbol: "₮",
    phone_code: "+976",
    emoji: "🇲🇳",
  },
  {
    name: "Montenegro",
    iso2: "ME",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+382",
    emoji: "🇲🇪",
  },
  {
    name: "Montserrat",
    iso2: "MS",
    currency: "xcd",
    currency_symbol: "$",
    phone_code: "+1-664",
    emoji: "🇲🇸",
  },
  {
    name: "Morocco",
    iso2: "MA",
    currency: "mad",
    currency_symbol: "DH",
    phone_code: "+212",
    emoji: "🇲🇦",
  },
  {
    name: "Mozambique",
    iso2: "MZ",
    currency: "mzn",
    currency_symbol: "MT",
    phone_code: "+258",
    emoji: "🇲🇿",
  },
  {
    name: "Myanmar",
    iso2: "MM",
    currency: "mmk",
    currency_symbol: "K",
    phone_code: "+95",
    emoji: "🇲🇲",
  },
  {
    name: "Namibia",
    iso2: "NA",
    currency: "nad",
    currency_symbol: "$",
    phone_code: "+264",
    emoji: "🇳🇦",
  },
  {
    name: "Nauru",
    iso2: "NR",
    currency: "aud",
    currency_symbol: "$",
    phone_code: "+674",
    emoji: "🇳🇷",
  },
  {
    name: "Nepal",
    iso2: "NP",
    currency: "npr",
    currency_symbol: "₨",
    phone_code: "+977",
    emoji: "🇳🇵",
  },
  {
    name: "Netherlands",
    iso2: "NL",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+31",
    emoji: "🇳🇱",
  },
  {
    name: "New Caledonia",
    iso2: "NC",
    currency: "xpf",
    currency_symbol: "₣",
    phone_code: "+687",
    emoji: "🇳🇨",
  },
  {
    name: "New Zealand",
    iso2: "NZ",
    currency: "nzd",
    currency_symbol: "$",
    phone_code: "+64",
    emoji: "🇳🇿",
  },
  {
    name: "Nicaragua",
    iso2: "NI",
    currency: "nio",
    currency_symbol: "C$",
    phone_code: "+505",
    emoji: "🇳🇮",
  },
  {
    name: "Niger",
    iso2: "NE",
    currency: "xof",
    currency_symbol: "CFA",
    phone_code: "+227",
    emoji: "🇳🇪",
  },
  {
    name: "Nigeria",
    iso2: "NG",
    currency: "ngn",
    currency_symbol: "₦",
    phone_code: "+234",
    emoji: "🇳🇬",
  },
  {
    name: "Niue",
    iso2: "NU",
    currency: "nzd",
    currency_symbol: "$",
    phone_code: "+683",
    emoji: "🇳🇺",
  },
  {
    name: "Norfolk Island",
    iso2: "NF",
    currency: "aud",
    currency_symbol: "$",
    phone_code: "+672",
    emoji: "🇳🇫",
  },
  {
    name: "North Korea",
    iso2: "KP",
    currency: "kpw",
    currency_symbol: "₩",
    phone_code: "+850",
    emoji: "🇰🇵",
  },
  {
    name: "Northern Mariana Islands",
    iso2: "MP",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+1-670",
    emoji: "🇲🇵",
  },
  {
    name: "Norway",
    iso2: "NO",
    currency: "nok",
    currency_symbol: "kr",
    phone_code: "+47",
    emoji: "🇳🇴",
  },
  {
    name: "Oman",
    iso2: "OM",
    currency: "omr",
    currency_symbol: ".ع.ر",
    phone_code: "+968",
    emoji: "🇴🇲",
  },
  {
    name: "Pakistan",
    iso2: "PK",
    currency: "pkr",
    currency_symbol: "₨",
    phone_code: "+92",
    emoji: "🇵🇰",
  },
  {
    name: "Palau",
    iso2: "PW",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+680",
    emoji: "🇵🇼",
  },
  {
    name: "Palestinian Territory Occupied",
    iso2: "PS",
    currency: "ils",
    currency_symbol: "₪",
    phone_code: "+970",
    emoji: "🇵🇸",
  },
  {
    name: "Panama",
    iso2: "PA",
    currency: "pab",
    currency_symbol: "B/.",
    phone_code: "+507",
    emoji: "🇵🇦",
  },
  {
    name: "Papua new Guinea",
    iso2: "PG",
    currency: "pgk",
    currency_symbol: "K",
    phone_code: "+675",
    emoji: "🇵🇬",
  },
  {
    name: "Paraguay",
    iso2: "PY",
    currency: "pyg",
    currency_symbol: "₲",
    phone_code: "+595",
    emoji: "🇵🇾",
  },
  {
    name: "Peru",
    iso2: "PE",
    currency: "pen",
    currency_symbol: "S/.",
    phone_code: "+51",
    emoji: "🇵🇪",
  },
  {
    name: "Philippines",
    iso2: "PH",
    currency: "php",
    currency_symbol: "₱",
    phone_code: "+63",
    emoji: "🇵🇭",
  },
  {
    name: "Pitcairn Island",
    iso2: "PN",
    currency: "nzd",
    currency_symbol: "$",
    phone_code: "+870",
    emoji: "🇵🇳",
  },
  {
    name: "Poland",
    iso2: "PL",
    currency: "pln",
    currency_symbol: "zł",
    phone_code: "+48",
    emoji: "🇵🇱",
  },
  {
    name: "Portugal",
    iso2: "PT",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+351",
    emoji: "🇵🇹",
  },
  {
    name: "Puerto Rico",
    iso2: "PR",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+1-787 and 1-939",
    emoji: "🇵🇷",
  },
  {
    name: "Qatar",
    iso2: "QA",
    currency: "qar",
    currency_symbol: "ق.ر",
    phone_code: "+974",
    emoji: "🇶🇦",
  },
  {
    name: "Reunion",
    iso2: "RE",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+262",
    emoji: "🇷🇪",
  },
  {
    name: "Romania",
    iso2: "RO",
    currency: "ron",
    currency_symbol: "lei",
    phone_code: "+40",
    emoji: "🇷🇴",
  },
  {
    name: "Russia",
    iso2: "RU",
    currency: "rub",
    currency_symbol: "₽",
    phone_code: "+7",
    emoji: "🇷🇺",
  },
  {
    name: "Rwanda",
    iso2: "RW",
    currency: "rwf",
    currency_symbol: "FRw",
    phone_code: "+250",
    emoji: "🇷🇼",
  },
  {
    name: "Saint Helena",
    iso2: "SH",
    currency: "shp",
    currency_symbol: "£",
    phone_code: "+290",
    emoji: "🇸🇭",
  },
  {
    name: "Saint Kitts And Nevis",
    iso2: "KN",
    currency: "xcd",
    currency_symbol: "$",
    phone_code: "+1-869",
    emoji: "🇰🇳",
  },
  {
    name: "Saint Lucia",
    iso2: "LC",
    currency: "xcd",
    currency_symbol: "$",
    phone_code: "+1-758",
    emoji: "🇱🇨",
  },
  {
    name: "Saint Pierre and Miquelon",
    iso2: "PM",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+508",
    emoji: "🇵🇲",
  },
  {
    name: "Saint Vincent And The Grenadines",
    iso2: "VC",
    currency: "xcd",
    currency_symbol: "$",
    phone_code: "+1-784",
    emoji: "🇻🇨",
  },
  {
    name: "Saint-Barthelemy",
    iso2: "BL",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+590",
    emoji: "🇧🇱",
  },
  {
    name: "Saint-Martin (French part)",
    iso2: "MF",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+590",
    emoji: "🇲🇫",
  },
  {
    name: "Samoa",
    iso2: "WS",
    currency: "wst",
    currency_symbol: "SAT",
    phone_code: "+685",
    emoji: "🇼🇸",
  },
  {
    name: "San Marino",
    iso2: "SM",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+378",
    emoji: "🇸🇲",
  },
  {
    name: "Sao Tome and Principe",
    iso2: "ST",
    currency: "std",
    currency_symbol: "Db",
    phone_code: "+239",
    emoji: "🇸🇹",
  },
  {
    name: "Saudi Arabia",
    iso2: "SA",
    currency: "sar",
    currency_symbol: "﷼",
    phone_code: "+966",
    emoji: "🇸🇦",
  },
  {
    name: "Senegal",
    iso2: "SN",
    currency: "xof",
    currency_symbol: "CFA",
    phone_code: "+221",
    emoji: "🇸🇳",
  },
  {
    name: "Serbia",
    iso2: "RS",
    currency: "rsd",
    currency_symbol: "din",
    phone_code: "+381",
    emoji: "🇷🇸",
  },
  {
    name: "Seychelles",
    iso2: "SC",
    currency: "scr",
    currency_symbol: "SRe",
    phone_code: "+248",
    emoji: "🇸🇨",
  },
  {
    name: "Sierra Leone",
    iso2: "SL",
    currency: "sll",
    currency_symbol: "Le",
    phone_code: "+232",
    emoji: "🇸🇱",
  },
  {
    name: "Singapore",
    iso2: "SG",
    currency: "sgd",
    currency_symbol: "$",
    phone_code: "+65",
    emoji: "🇸🇬",
  },
  {
    name: "Sint Maarten (Dutch part)",
    iso2: "SX",
    currency: "ang",
    currency_symbol: "ƒ",
    phone_code: "+1721",
    emoji: "🇸🇽",
  },
  {
    name: "Slovakia",
    iso2: "SK",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+421",
    emoji: "🇸🇰",
  },
  {
    name: "Slovenia",
    iso2: "SI",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+386",
    emoji: "🇸🇮",
  },
  {
    name: "Solomon Islands",
    iso2: "SB",
    currency: "sbd",
    currency_symbol: "Si$",
    phone_code: "+677",
    emoji: "🇸🇧",
  },
  {
    name: "Somalia",
    iso2: "SO",
    currency: "sos",
    currency_symbol: "Sh.so.",
    phone_code: "+252",
    emoji: "🇸🇴",
  },
  {
    name: "South Africa",
    iso2: "ZA",
    currency: "zar",
    currency_symbol: "R",
    phone_code: "+27",
    emoji: "🇿🇦",
  },
  {
    name: "South Georgia",
    iso2: "GS",
    currency: "gbp",
    currency_symbol: "£",
    phone_code: "+500",
    emoji: "🇬🇸",
  },
  {
    name: "South Korea",
    iso2: "KR",
    currency: "krw",
    currency_symbol: "₩",
    phone_code: "+82",
    emoji: "🇰🇷",
  },
  {
    name: "South Sudan",
    iso2: "SS",
    currency: "ssp",
    currency_symbol: "£",
    phone_code: "+211",
    emoji: "🇸🇸",
  },
  {
    name: "Spain",
    iso2: "ES",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+34",
    emoji: "🇪🇸",
  },
  {
    name: "Sri Lanka",
    iso2: "LK",
    currency: "lkr",
    currency_symbol: "Rs",
    phone_code: "+94",
    emoji: "🇱🇰",
  },
  {
    name: "Sudan",
    iso2: "SD",
    currency: "sdg",
    currency_symbol: ".س.ج",
    phone_code: "+249",
    emoji: "🇸🇩",
  },
  {
    name: "Suriname",
    iso2: "SR",
    currency: "srd",
    currency_symbol: "$",
    phone_code: "+597",
    emoji: "🇸🇷",
  },
  {
    name: "Svalbard And Jan Mayen Islands",
    iso2: "SJ",
    currency: "nok",
    currency_symbol: "kr",
    phone_code: "+47",
    emoji: "🇸🇯",
  },
  {
    name: "Swaziland",
    iso2: "SZ",
    currency: "szl",
    currency_symbol: "E",
    phone_code: "+268",
    emoji: "🇸🇿",
  },
  {
    name: "Sweden",
    iso2: "SE",
    currency: "sek",
    currency_symbol: "kr",
    phone_code: "+46",
    emoji: "🇸🇪",
  },
  {
    name: "Switzerland",
    iso2: "CH",
    currency: "chf",
    currency_symbol: "CHf",
    phone_code: "+41",
    emoji: "🇨🇭",
  },
  {
    name: "Syria",
    iso2: "SY",
    currency: "syp",
    currency_symbol: "LS",
    phone_code: "+963",
    emoji: "🇸🇾",
  },
  {
    name: "Taiwan",
    iso2: "TW",
    currency: "twd",
    currency_symbol: "$",
    phone_code: "+886",
    emoji: "🇹🇼",
  },
  {
    name: "Tajikistan",
    iso2: "TJ",
    currency: "tjs",
    currency_symbol: "SM",
    phone_code: "+992",
    emoji: "🇹🇯",
  },
  {
    name: "Tanzania",
    iso2: "TZ",
    currency: "tzs",
    currency_symbol: "TSh",
    phone_code: "+255",
    emoji: "🇹🇿",
  },
  {
    name: "Thailand",
    iso2: "TH",
    currency: "thb",
    currency_symbol: "฿",
    phone_code: "+66",
    emoji: "🇹🇭",
  },
  {
    name: "Togo",
    iso2: "TG",
    currency: "xof",
    currency_symbol: "CFA",
    phone_code: "+228",
    emoji: "🇹🇬",
  },
  {
    name: "Tokelau",
    iso2: "TK",
    currency: "nzd",
    currency_symbol: "$",
    phone_code: "+690",
    emoji: "🇹🇰",
  },
  {
    name: "Tonga",
    iso2: "TO",
    currency: "top",
    currency_symbol: "$",
    phone_code: "+676",
    emoji: "🇹🇴",
  },
  {
    name: "Trinidad And Tobago",
    iso2: "TT",
    currency: "ttd",
    currency_symbol: "$",
    phone_code: "+1-868",
    emoji: "🇹🇹",
  },
  {
    name: "Tunisia",
    iso2: "TN",
    currency: "tnd",
    currency_symbol: "ت.د",
    phone_code: "+216",
    emoji: "🇹🇳",
  },
  {
    name: "Turkey",
    iso2: "TR",
    currency: "try",
    currency_symbol: "₺",
    phone_code: "+90",
    emoji: "🇹🇷",
  },
  {
    name: "Turkmenistan",
    iso2: "TM",
    currency: "tmt",
    currency_symbol: "T",
    phone_code: "+993",
    emoji: "🇹🇲",
  },
  {
    name: "Turks And Caicos Islands",
    iso2: "TC",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+1-649",
    emoji: "🇹🇨",
  },
  {
    name: "Tuvalu",
    iso2: "TV",
    currency: "aud",
    currency_symbol: "$",
    phone_code: "+688",
    emoji: "🇹🇻",
  },
  {
    name: "Uganda",
    iso2: "UG",
    currency: "ugx",
    currency_symbol: "USh",
    phone_code: "+256",
    emoji: "🇺🇬",
  },
  {
    name: "Ukraine",
    iso2: "UA",
    currency: "uah",
    currency_symbol: "₴",
    phone_code: "+380",
    emoji: "🇺🇦",
  },
  {
    name: "United Arab Emirates",
    iso2: "AE",
    currency: "aed",
    currency_symbol: "إ.د",
    phone_code: "+971",
    emoji: "🇦🇪",
  },
  {
    name: "United Kingdom",
    iso2: "GB",
    currency: "gbp",
    currency_symbol: "£",
    phone_code: "+44",
    emoji: "🇬🇧",
  },
  {
    name: "United States",
    iso2: "US",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+1",
    emoji: "🇺🇸",
  },
  {
    name: "United States Minor Outlying Islands",
    iso2: "UM",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+1",
    emoji: "🇺🇲",
  },
  {
    name: "Uruguay",
    iso2: "UY",
    currency: "uyu",
    currency_symbol: "$",
    phone_code: "+598",
    emoji: "🇺🇾",
  },
  {
    name: "Uzbekistan",
    iso2: "UZ",
    currency: "uzs",
    currency_symbol: "лв",
    phone_code: "+998",
    emoji: "🇺🇿",
  },
  {
    name: "Vanuatu",
    iso2: "VU",
    currency: "vuv",
    currency_symbol: "VT",
    phone_code: "+678",
    emoji: "🇻🇺",
  },
  {
    name: "Vatican City State (Holy See)",
    iso2: "VA",
    currency: "eur",
    currency_symbol: "€",
    phone_code: "+379",
    emoji: "🇻🇦",
  },
  {
    name: "Venezuela",
    iso2: "VE",
    currency: "vef",
    currency_symbol: "Bs",
    phone_code: "+58",
    emoji: "🇻🇪",
  },
  {
    name: "Vietnam",
    iso2: "VN",
    currency: "vnd",
    currency_symbol: "₫",
    phone_code: "+84",
    emoji: "🇻🇳",
  },
  {
    name: "Virgin Islands (British)",
    iso2: "VG",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+1-284",
    emoji: "🇻🇬",
  },
  {
    name: "Virgin Islands (US)",
    iso2: "VI",
    currency: "usd",
    currency_symbol: "$",
    phone_code: "+1-340",
    emoji: "🇻🇮",
  },
  {
    name: "Wallis And Futuna Islands",
    iso2: "WF",
    currency: "xpf",
    currency_symbol: "₣",
    phone_code: "+681",
    emoji: "🇼🇫",
  },
  {
    name: "Western Sahara",
    iso2: "EH",
    currency: "mad",
    currency_symbol: "MAD",
    phone_code: "+212",
    emoji: "🇪🇭",
  },
  {
    name: "Yemen",
    iso2: "YE",
    currency: "yer",
    currency_symbol: "﷼",
    phone_code: "+967",
    emoji: "🇾🇪",
  },
  {
    name: "Zambia",
    iso2: "ZM",
    currency: "zmw",
    currency_symbol: "ZK",
    phone_code: "+260",
    emoji: "🇿🇲",
  },
  {
    name: "Zimbabwe",
    iso2: "ZW",
    currency: "zwl",
    currency_symbol: "$",
    phone_code: "+263",
    emoji: "🇿🇼",
  },
];
